source 'http://rubygems.org'

gem 'rack', '1.4.5'
gem 'sinatra', '1.4.3'
gem 'omniauth', '1.1.4'
gem 'haml', '4.0.3'
gem 'redis', '3.0.4'
gem 'rspec', '2.14.1'
gem 'omniauth-twitter', :github => 'arunagw/omniauth-twitter'
gem 'omniauth-github', :github => 'intridea/omniauth-github'
gem 'omniauth-facebook'
gem 'pry'
