require 'yaml'
require 'omniauth'
require 'omniauth-twitter'
require 'omniauth-github'
require 'omniauth-facebook'
require 'sinatra'
require 'haml'
require 'redis'
require 'json'

require_relative 'helpers/challenge_helper'
require_relative 'models/invite'
require_relative 'models/user'
require_relative 'repositories/invite_repository'
require_relative 'repositories/user_repository'
require_relative 'twitter'
require_relative 'facebook'
require_relative 'github'
require_relative 'gym_today_server'

